name: Deploy to Staging Spreadsheet

on:
  push:
    branches:
      - main  # 當 main 分支有更新時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Create .clasprc.json for auth
      run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

    - name: Verify .clasprc.json content
      run: |
        echo '--- Start of .clasprc.json content ---'
        cat ~/.clasprc.json
        echo '--- End of .clasprc.json content ---'

    - name: Create .clasp.json for target
      run: |
        cat <<EOF > .clasp.json
        {
          "scriptId": "${{ secrets.STAGING_SCRIPT_ID }}",
          "rootDir": "${{ secrets.ROOT_DIR }}"
          "scriptExtensions": [
              ".js",
              ".gs"
            ],
            "htmlExtensions": [
              ".html"
            ],
            "jsonExtensions": [
              ".json"
            ],
            "filePushOrder": [],
            "skipSubdirectories": false
        }
        EOF

    - name: Push to Google Apps Script
      run: clasp push -f
